[registries.crates-io]
protocol = "sparse"

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]

[env]
RUST_BACKTRACE = "full"

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "./third-party/vendor/"